/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   parser.c                                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: gkhavari <gkhavari@student.42vienna.c      +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/11/29 20:21:00 by gkhavari          #+#    #+#             */
/*   Updated: 2025/12/05 22:42:06 by gkhavari         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "minishell.h"
/**
 DESCRIPTION:
* Allocates and initializes a new t_command structure.
* Everything is initiallized to 0/NULL.

RETURN VALUE:
* A pointer to a newly allocated and initialized t_command structure.
* NULL if memory allocation fails.
**/
t_command	*new_command(void)
{
	t_command	*cmd;

	cmd = malloc(sizeof(t_command));
	if (!cmd)
		return (NULL);
	cmd->args = NULL;
	cmd->argv = NULL;
	cmd->input_file = NULL;
	cmd->output_file = NULL;
	cmd->append = 0;
	cmd->is_builtin = 0;
	cmd->next = NULL;
	return (cmd);
}

/**
 DESCRIPTION:
* Parses a linked list of tokens and builds a linked list of t_command 
	structures.
* Each occurrence of a PIPE token indicates the start of a new command, 
	causing a new t_command to be allocated.
* Non-pipe tokens are processed and assigned to the current command via
	add_token_to_command().

PARAMETERS:
* token: A pointer to the head of the tokenlist generated by the tokenizer.

RETURN:
* A pointer to the head of the newly built command list.
* The list will contain at least one command, even if no pipe tokens were found.
 **/
t_command	*parse_tokens(t_token *token)
{
	t_command	*head;
	t_command	*cmd;

	head = new_command();
	cmd = head;
	while (token)
	{
		if (token->type == PIPE)
		{
			cmd->next = new_command();
			cmd = cmd->next;
		}
		else
			add_token_to_command(cmd, token);
		token = token->next;
	}
	return (head);
}

/**
 DESCRIPTION:
* High-level parsing function that takes the already-tokenized shell input 
	and constructs
	the final command list.
* It first checks syntax validity, and if no errors are present, builds 
	the command list and performs post-processing.

PARAMETERS:
* shell: A pointer to the main shell structure, containing tokens and
	a location to store parsed commands.

BEHAVIOR:
* Calls syntax_check(shell->tokens)
* If a syntax error is detected, the function immediately returns without
	altering shell->commands.
* Calls parse_tokens() to turn tokens into a command list.
* Calls finalize_all_commands() to perform final adjustments 
	(e.g., building argv, resolving redirections, etc.).
**/
void	parse_input(t_shell *shell)
{
	if (syntax_check(shell->tokens))
		return ;
	shell->commands = parse_tokens(shell->tokens);
	finalize_all_commands(shell->commands);
}
